### ISSUE TITLE
Microsoft Edge not compatible

### ISSUE THREAD

**Issue by rmeske** [mantisbt-plugins/Taskodrome#94] opened 2017-02-07 21:23 UTC
Hello,

When using Microsoft Edge, the view for Taskodrome has the MantiBT header expanded to cover half the window.  Using MantisBT version 2.1.0
![taskodrome-edge-issue](https://cloud.githubusercontent.com/assets/3299975/22712133/8830b038-ed38-11e6-9c62-87bd5a290cc7.PNG)

**Comment by vboctor** [comment] 2017-02-07 21:27
This is typically caused by one of the source files included not having the appropriate UTF-8 byte marker.

**Comment by AuthenticEshkinKot** [comment] 2017-02-08 08:46
@vboctor 
Do you speak about BOM (Byte Order Marker)?

**Comment by atrol** [comment] 2017-02-08 08:55
Files must **not** include BOM.
Furthermore remove white spaces after closing PHP tag if there is a closing tag at the end of a file (or even better, remove the tag)
E.g. there is one at https://github.com/mantisbt-plugins/Taskodrome/blob/master/Taskodrome/pages/main.php

**Comment by jmascheri** [comment] 2017-02-08 16:36
I just tried ensuring that all pages are UTF8 and do **NOT** include BOM.  I also removed any closing PHP tags that I found at the end of PHP files. (I left config_page.php alone since it had multiple open and close PHP tags and the configuration page when run is working properly.)

Unfortunately these solutions did not solve the issue.

I did notice that in the CSS, there is no height specified for the header. If i add a height to the `<div id="navbar">` container in the DOM inspector, it solves the issue.  Or if I remove the 100% height from the `<ul class="ace-nav">` this also solves the problem.  However, I am unaware of any potential consequences of applying these edits to the CSS as I do not know what else may be reliant on these styles.

**Comment by AuthenticEshkinKot** [comment] 2017-02-08 21:33
@jmascheri 
Thanks for testing! Unfortunately, I have no copy of Edge, so I can't test Taskodrome with it. 
As far as I can see, you found that bug is connected not with the plugin itself, but with tracker's styles. Could you create a bugreport for mantisbt?

**Comment by jmascheri** [comment] 2017-02-08 22:03
@AuthenticEshkinKot

I can do this but I am not sure exactly how to describe the issue on the mantisbt issue tracker.  From what I have seen, the mantisbt styles are working properly across all mantisbt pages.  The only place we have found this issue is on the Taskodrome page.  Even the Config page for Taskodrome appears properly.

Should I simply mention that the issue is happening with the Taskodrome plugin and reference this issue?

Please advise.

**Comment by vboctor** [comment] 2017-02-09 06:41
@jmascheri This is not a bug in MantisBT core.  It is likely that either your `config_inc.php`, `custom_strings_inc.php`, etc or one of the Taskdrome files has byte order marker at the beginning.  You can fix that by using Sublime Text Editor as saving as UTF8 without BOM.

An easy way to test the source is to disable the Taskdrome plugin and see if the bug still exists.

Typically when this happens, other browsers are affected as well, but not as bad as Edge.

**Comment by jmascheri** [comment] 2017-02-09 15:59
@vboctor It didnt seem like an issue with the MantisBT core to me either as, like you mentioned, the rest of mantis is working fine.  Unfortunately, I cannot perform the test that you mentioned because the issue only occurs on the Taskodrome plugin page and no others in Mantis.

I have already converted all of the Taskodrome files to UTF-8 without BOM and I believe that I did the same with my config_inc and custom_strings_inc files.  However, I will double check them now to be sure.

If this doesnt work, I will probably just edit the CSS file for the page to include a height for the header which fixed the issue when I applied the style in the DOM but it leaves the "Report Issue" button and the Avatar icon uncentered in the header as you can see in the screenshot above.

Thanks for trying to help with this issue guys!

**Comment by ivan-perl** [comment] 2017-03-30 09:06
I figured out why this happens. Generated page is wrong and Edge just appears less tolerant to it than other browsers. Here is what I see in DOM explorer in Edge:

```
link rel="stylesheet" type="text/css" href="/mantisbt-2.2.1/plugin_file.php?file=Taskodrome/taskodrome.css"/>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/easeljs-0.8.2.min.js"></script>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/grid_common_utils.js"></script>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/grid_draw_utils.js"></script>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/devs_grid.js"></script>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/status_grid.js"></script>
<script type="text/javascript" src="./plugins/Taskodrome/scripts/on_load_opening.js"></script>

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta name="robots" content="noindex,follow" />
	<title>Taskodrome - MantisBT</title>
```

So, all your JavaScripts and CSS references are inserted before the <head> and even before the beginning HTML document.

I've updated you main php file called main.php and placed references to CSS and JS between start and end of the header borders like this:

```
layout_page_header_begin(plugin_lang_get( 'board' ));
    echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"./plugins/Taskodrome/files/taskodrome.css\"/>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/easeljs-0.8.2.min.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/grid_common_utils.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/grid_draw_utils.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/devs_grid.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/status_grid.js\"></script>\n";
    echo "<script type=\"text/javascript\" src=\"./plugins/Taskodrome/scripts/on_load_opening.js\"></script>\n";
  layout_page_header_end();
```

And generated DOM beginning became:

```
    <script type="text/javascript" src="./plugins/Taskodrome/scripts/on_load_opening.js"></script>
    <script src="/mantisbt-2.2.1/plugin_file.php?file=MantisGraph/chart-2.1.6.min.js"></script>
    <script src="/mantisbt-2.2.1/plugin_file.php?file=MantisGraph/chart.bundle-2.1.6.min.js"></script>
    <script src="/mantisbt-2.2.1/plugin_file.php?file=MantisGraph/MantisGraph.js"></script>
</head>
<body class="skin-3">
```

-------
Ivan from sdCloud.io team

**Comment by AuthenticEshkinKot** [comment] 2017-04-01 20:53
@rmeske 
I've made a fix for this issue. Check it out, please.

**Comment by rmeske** [comment] 2017-04-03 15:14
@AuthenticEshkinKot , Thank you that resolved the issue.

**Closed** 2017-04-03 19:15 UTC
Labels: bug
