### ISSUE TITLE
Relations between issues are not shown on Relationships board

### ISSUE THREAD

**Issue by skechav** [mantisbt-plugins/Taskodrome#280] opened 2019-04-04 14:32 UTC
Just installed the Taskdrome plugin on a fresh Mantisbt installation .The "defect" is **as described in the title.** It justs outputs the image with the following text on it : 
"No Relations between issues" . Though, the 2 test issues are clearly related to each other on Mantis "View Issue Details" dashboard.
Also, I think I should note that it might be a Mantis issue in fact cause I cant see the relation graph or dependency graph of Mantis as well.
Any thoughts?
**System description :**
OpenResty
NginX
PHP 7.3
MantisBT Version | 2.18.0
Database Driver | mysqli

Thanks in advance !

**Comment by skechav** [comment] 2019-04-04 14:59
**RESOLVED** : IT is **NOT** an issue really. Someone just need to set 
 $g_relationship_graph_enable = ON;
in [mantis isntallation folder]/config_defaults.inc.php

**Comment by AuthenticEshkinKot** [comment] 2019-04-04 16:39
Hello, @skechav !
If the problem is solved, then I'll close this issue.

**Closed** 2019-04-09 08:29 UTC
