### ISSUE TITLE
Move a issue have no effect on the issue values

### ISSUE THREAD

**Issue by ducemmanuel** [mantisbt-plugins/Taskodrome#9] opened 2016-02-16 09:37 UTC
Hello,

I can change on the screen Taskodrome the value for fields "assigned to" & "Status", but there is no commit. When I re-open the issue values have not changed.

Best regards
Emmanuel.

**Comment by johnzastrow** [comment] 2016-02-25 18:25
Confirmed. Fairly fresh install of v 1.2.19 and the tiles move happily around the screen, but the changes do not stick... consistently. They do seem to work some of the time. Not sure if there is a log of errors any where that I can show.

**Comment by AuthenticEshkinKot** [comment] 2016-02-25 19:20
@ducemmanuel @johnzastrow  Excuse me, but could you describe steps to reproduce this bug?

**Comment by johnzastrow** [comment] 2016-02-25 19:58
Sure. 
1. Login (as an admin user)
2. Click Taskodrome (with a project selected in upper right)
3. See issues (lots - feature request for filters at top of screen)
4. Choose Assignment Board
5. Grab issue from the unassigned list on the left (confirmed status)
6. Drag into my user column
7. Note issue ID and enter into little search window in upper right to view issue details
8. Determined that no change was made to the issue and it was not assigned to me
------
Switch project in upper right
5b. Grab issue from my assignment list (status = Closed) and 
6b. drag to left most column
7b. ""
8b. Determined that the change DID happen this time and the issue is no longer assigned to me. Status remained Closed.

Having some means to log events to help debug this might be nice.

**Comment by johnzastrow** [comment] 2016-02-25 19:59
Great plugin BTW. Just what I was hoping for. Few more features will make it even better. Thank you.

**Comment by AuthenticEshkinKot** [comment] 2016-02-27 12:16
@johnzastrow Thank you!
I've updated the project, now it emits some log messages when user work with "Assignment board". Could you repeat your steps in "Assignment board" and post logs which will appear?

**Comment by johnzastrow** [comment] 2016-03-01 21:53
I can't seem to break it anymore :-) But where do I find the logs?

**Comment by AuthenticEshkinKot** [comment] 2016-03-03 11:58
@johnzastrow Sounds good, although I don't know how can this commit help :)
Logs can be found in browser's console, which can be opened by F12 in Firefox and Chrome. I don't know about other mainstream browsers, but I'm pretty sure that they have console too.

**Closed** 2016-07-01 18:49 UTC
Labels: bug
